default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: statbet_development

test:
  <<: *default
  database: statbet_test

production:
  <<: *default
  database: statbet_production
  username: statbet
  password: <%= ENV['VICECOP_DATABASE_PASSWORD'] %>
